name: test_build_deploy
on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
  workflow_dispatch:
permissions: 
  contents: write
  id-token: write
  security-events: write
concurrency:
  group: ${{github.ref}}-ci
  cancel-in-progress: true
env:
  REGION: ${{vars.AWS_REGION}}
  ROLE: ${{secrets.ROLE}}
  REPO: ${{vars.ECR_REPO}}
  REG: ${{vars.ECR_REG}}
  PYTHON: '3.11'
  IMAGE_TAG: ${{github.sha}}
  Email: ${{secrets.Email}}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup python 
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON}}
          cache: 'pip'
      - name: install dependency 
        run: |
          pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: run test 
        run: pytest src/* -v --maxfail=1 --disable-warnings --cov=. --cov-report=term-missing
      - name: run linting of code 
        run: flake8 . --count --max-line-length=120 --statistics
      - name: check code vulnerabilities
        run: bandit -r . -l -s B101,B103,B104,B105
      - name: check for dependency vulnerabilities
        run: check safety --full-report || true 
    #===============
    #build
    #===============
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      image-tag: ${{steps.meta.outputs.tags}}
    needs: test
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
        with: 
          fetch-depth: 1
      - name: seutup docker build environement
        uses: docker/setup-buildx-action@v3
      - name: use cache for faster build
        uses: actions/cache@v4
        with:
          path: ./buildx
          key: ${{runner.os}}-buildx-${{github.sha}}
          restore-keys: |
            ${{runner.os}}-buildx-
      - name: generate metadata tag and label
        id: meta 
        uses: docker/metadata-action@v5
        with:
          images: ${{env.REG}}${{env.REPO}}
          tags: |
            type=sha
            type=raw,value=latest
      - name: build images 
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          platforms: linux/amd64
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: check if images has been build 
        run: docker images
      - name: save images
        run: docker save ${{env.REG}}${{env.REPO}}: -o images.tar
      - name: upload artifact to github blob storage
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: images.tar
          retention-days: 7

 #==============
 #scan_images
 #=============
  scan_images: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: get images 
        uses: actions/download-artifact@v4
        with:
          name: images
          path: .
      - name: setup docker buildx 
        uses: docker/setup-buildx-action@v3
      - name: load image to local daemon
        run: docker load -i images.tar
      - name: scan images for vulnerabilities
        uses: aquasecurity/trivy-action@0.33.0
        with:
          image-ref: ${{env.REG}}${{env.REPO}}:latest
          format: table
          ignore-unfixed: true #ignore issues that cant be patch with os, library
          exit-code: 0 # if caught an error only raise a warning and not fail pipeline
          severity: HIGH
          vuln-type: 'os,library'

  #================
  #test image
  #============
  testing:
    need: scan
    runs-on: ubuntu-latest
    steps:
      - name: download artifact 
        uses: actions/download-artifact@v4
        with:
          name: images
          path: .
      - name: load image into daemon 
        run: docker load -i images.tar
      - name: run test on image 
       
#=============
#push
#==================
  push:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.ref == 'refs/heads/main' 
    steps:
      - name: download artifact 
        uses: actions/download-artifact@v4
        with:
          name: images
          path: .
      - name: check if images has been downloaded
        run: docker images
      - name: load artifact to local daemon 
        run: docker load -i images.tar
      - name: login to amazon 
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: ${{env.ROLE}}
          aws-region: ${{env.REGION}}
      - name: login to ecr 
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: push to aws 
        run: | 
          docker tag ${{env.REG}}${{env.REPO}}:latest ${{env.REG}}${{env.REPO}}:${{env.IMAGE_TAG}}
          docker push ${{env.REG}}${{env.REPO}}:latest
          docker push ${{env.REG}}${{env.REPO}}:${{env.IMAGE_TAG}}
      - name: send notification to email
        run: |
          aws sns publish \
          --topic-arn ${{env.Email}} \
          --subject "workflow successful" \
          --message "The pipeline ran successfully and the image with ID: ${{env.REG}}${{env.REPO}}"
